language: python
branches:
  only:
  - content
install:
- pip install pelican ghp-import markdown

before_script:
- pelican-themes -i ./themes/eevee

script:
- make publish
- make github
env:
  global:
    secure: H8dJCGq/raqnNEWPdPXeGTRfgvB/ozrJeNZVqoJ5uflO6kapFFOQAVRcBX27JIOuVQo9HcO3qhQGRG4XJN0l68Jer77fGbOegCc7ozSVwCOL8Zo7JKjhHrkJFXOIZOijLMN2kZTpXycHHKKMeR1SYVjQ2yoTe7gn3IineztrLVrg2nYyZCOTB3Hr+TGTk4lp7+BeOsgxlGK38RlvEtD7c/EBCpHka+FKn8B9HE7mIeRBnt5fLGI++vBBskXYPS8KmilGyMdAnHVbA5xITRmE6TJNwN8bb0gA4MV3mhpP3EmzIxTXQrdcKacvCZVLK/h1hWRvMgxdY2U7qKM5r3E3g3kG2kHjY6CCUbfar9dFpXSZj3kpHpAWktOZ8gBQdEsZJ9rX82X/d+yJ+I78mYk6zPirMtibZ9yM2c+G8MbKvUaf/JVgfQPXj1bavWpAa15r9jzBWIRkuOtOE/MYJtZCg0HdgmqfSEEHzualsOTfeQNcrZPztHiOKkYThuDkeyOI8S6Q/H+o0IDldCOFV0NRTVO4fH1zpH7zmII4H5pf5UwUdKriz8J0eWuKZdbE7/ajYa5modYyGrDTjvOg/ux/S+8nzj9yKXOqwBsTzGOVwoXjumAj07TEe5zYCpBgBbl/yh5baEcrNGwXjPsk98ki/fzPRXQ3p7Zk9rp/6q2xzbU=
